name: coshan
version: 0.1.0.0
github: "timlathy/coshan"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- bytestring
- elf
- regex-tdfa
- split

library:
  source-dirs: src
  cc-options: -fPIC
  extra-libraries: LLVM-11

executables:
  coshan-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coshan
    - cmdargs
    - pretty-simple

tests:
  coshan-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coshan
    - hspec
    - hspec-megaparsec
    - directory
    - process
    - pureMD5
    - string-interpolate
    - utility-ht
