resolver: lts-18.28
packages:
- .
extra-deps:
- bytestring-0.11.1.0
- binary-0.8.9.0
- process-1.6.14.0
- directory-1.3.6.1
- unix-2.7.2.2
- text-1.2.5.0
- Cabal-3.4.1.0
- parsec-3.1.15.1
allow-newer: true
