resolver: lts-17.10
packages:
- .
extra-deps:
- bytestring-0.11.1.0
- binary-0.8.8.0
- process-1.6.11.0
- directory-1.3.6.1
- unix-2.7.2.2
- text-1.2.4.1
- Cabal-3.4.0.0
- parsec-3.1.14.0
allow-newer: true
